### ISSUE TITLE
[Feature request] Disable formatting on a per-project basis

### ISSUE THREAD

**Issue by marmistrz** [AtomFormatter/formatter#10]
We often have legacy code which we don't want to format. It would be great to disable formatter on a per-project basis.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom-community/formatter), this package is no longer maintained and is deprecated. We recommend that people use the [Atom IDE feature](https://ide.atom.io/) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
