### ISSUE TITLE
"No code formatting providers found" Error

### ISSUE THREAD

**Issue by udayms** [AtomFormatter/formatter#11]
I have the formatter package and the atom-formatter-jsbeautify package installed. Yet, when I click on 'Format Code' in the context menu, I get the following error: 
![screen shot 2017-09-14 at 2 36 52 pm](https://user-images.githubusercontent.com/186861/30456868-2d3202ee-995a-11e7-92c1-0dab4b03aebc.png)

**Comment by aditya-simplecrm** [comment]
any solution?

**Comment by axelosorio** [comment]
I have the same issue, The solution for me (and is not a solution per se) is click in menu/packages/atom Beautify/beautify
:-(

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom-community/formatter), this package is no longer maintained and is deprecated. We recommend that people use the [Atom IDE feature](https://ide.atom.io/) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
