### ISSUE TITLE
Restore cursor position after formatting

### ISSUE THREAD

**Issue by artagnon** [AtomFormatter/formatter#2]
Having to scroll back to my original location after each format is extremely annoying.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom-community/formatter), this package is no longer maintained and is deprecated. We recommend that people use the [Atom IDE feature](https://ide.atom.io/) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
