### ISSUE TITLE
Cannot format text selection

### ISSUE THREAD

**Issue by calebzulawski** [AtomFormatter/formatter#6]
I can not apply formatting to selected text.  I believe this is the offending block of code below:

``` coffeescript
else if provider.getNewText
  text = editor.getSelectedText()
  if !text
    selected = false
    text = editor.getText();
  return if !text
  newText = Promise.resolve(provider.getNewText(text))
  newText.then (newText) ->
    if (selected)
      editor.replaceSelectedText(newText)
    else
      editor.setText(newText)
```

`selected` is never set to `true`.  When set to `true`, `editor.replaceSelectedText(newText)` fails, because the expected argument is a function that operates on the selected text.

Since `selected` remains `undefined`, the entire text area is set to just the formatted selection.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom-community/formatter), this package is no longer maintained and is deprecated. We recommend that people use the [Atom IDE feature](https://ide.atom.io/) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
